name: money_care
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  http: ^1.3.0
  carousel_slider: ^5.0.0
  google_sign_in: ^7.2.0
  image_picker: ^1.1.2
  fl_chart: ^1.1.1
  flutter_svg: ^2.2.1
  dotted_border: ^2.0.0
  calendar_date_picker2: ^2.0.1
  flutter_dotenv: ^6.0.0
  percent_indicator: ^4.2.3 
  video_player: ^2.9.1
  speech_to_text: ^7.3.0

  # icons
  iconsax_flutter: ^1.0.0

  # state management
  get: 4.7.2
  get_storage: ^2.1.1
  shared_preferences: ^2.5.2
  flutter_custom_keyboard: ^1.1.1

  # firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  #------------------- Local Assets ------------------- #
  assets:
    - assets/images/
    - assets/icons/
    - .env

  #------------------- Local Fonts ------------------- #
  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 700